do
$$
begin


if not exists (select  1  from EPPS_ADMIN.EPPS_MISC_MST where misc_misc_cd = 'TETANUS_TOXOID' ) then
INSERT INTO EPPS_ADMIN.EPPS_MISC_MST
(COMP_CD, 		MISC_SR_NO,			MISC_MISC_CD,			MISC_MISC_NAME,
PARENT_MISC_CD,	EPPS_ONLY_FLAG,		MISC_VALUE,				REMARKS,
CREATED_BY,		CREATED_DT,			TERMINAL_ID,			ACTIVE_YN,
MISC_TYPE,		CREATOR_ROLE_CD,	MODULE_ID,				INSERT_ALLOW,
OPERATION_DONE)
VALUES(1,		COALESCE((SELECT MAX(MISC_SR_NO)+1 FROM EPPS_ADMIN.EPPS_MISC_MST),1),	'TETANUS_TOXOID',	'TETANUS TOXOID (TT)',
(SELECT MISC_SR_NO FROM EPPS_ADMIN.EPPS_MISC_MST WHERE MISC_MISC_CD = 'VACCINATION'),				0,		NULL,		NULL,
'P0000',		NOW(),		'UMA_BE',	1,
'VACCINATION',			2,			'INAYU',	'Y',
NULL);
end if;

if not exists (select  1  from EPPS_ADMIN.EPPS_MISC_MST where misc_misc_cd = 'TYPHOID' ) then
INSERT INTO EPPS_ADMIN.EPPS_MISC_MST
(COMP_CD, 		MISC_SR_NO,			MISC_MISC_CD,			MISC_MISC_NAME,
PARENT_MISC_CD,	EPPS_ONLY_FLAG,		MISC_VALUE,				REMARKS,
CREATED_BY,		CREATED_DT,			TERMINAL_ID,			ACTIVE_YN,
MISC_TYPE,		CREATOR_ROLE_CD,	MODULE_ID,				INSERT_ALLOW,
OPERATION_DONE)
VALUES(1,		COALESCE((SELECT MAX(MISC_SR_NO)+1 FROM EPPS_ADMIN.EPPS_MISC_MST),1),	'TYPHOID',	'TYPHOID',
(SELECT MISC_SR_NO FROM EPPS_ADMIN.EPPS_MISC_MST WHERE MISC_MISC_CD = 'VACCINATION'),				0,		NULL,		NULL,
'P0000',		NOW(),		'UMA_BE',	1,
'VACCINATION',			2,			'INAYU',	'Y',
NULL);
end if;

if not exists (select  1  from EPPS_ADMIN.EPPS_MISC_MST where misc_misc_cd = 'COVISHIELD' ) then
INSERT INTO EPPS_ADMIN.EPPS_MISC_MST
(COMP_CD, 		MISC_SR_NO,			MISC_MISC_CD,			MISC_MISC_NAME,
PARENT_MISC_CD,	EPPS_ONLY_FLAG,		MISC_VALUE,				REMARKS,
CREATED_BY,		CREATED_DT,			TERMINAL_ID,			ACTIVE_YN,
MISC_TYPE,		CREATOR_ROLE_CD,	MODULE_ID,				INSERT_ALLOW,
OPERATION_DONE)
VALUES(1,		COALESCE((SELECT MAX(MISC_SR_NO)+1 FROM EPPS_ADMIN.EPPS_MISC_MST),1),	'COVISHIELD',	'COVISHIELD',
(SELECT MISC_SR_NO FROM EPPS_ADMIN.EPPS_MISC_MST WHERE MISC_MISC_CD = 'VACCINATION'),				0,		NULL,		NULL,
'P0000',		NOW(),		'UMA_BE',	1,
'VACCINATION',			2,			'INAYU',	'Y',
NULL);
end if;
end;
$$;